name: Tests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'zulu'

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Maven Package
        run: mvn clean package

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: target/surefire-reports/**/*.xml

      - name: Validate GitHub Template
        run: cd infra/function && sam validate

      - name: Build GitHub Template
        run: cd infra/function && sam build
